/*==============================================================*/
/* DBMS name: MySQL 5.0 */
/* Generated by script                                          */
/*==============================================================*/
DROP DATABASE IF EXISTS happy_reading;
CREATE DATABASE happy_reading
  CHARACTER SET utf8
        DEFAULT CHARACTER SET utf8
        COLLATE utf8_unicode_ci
        DEFAULT COLLATE utf8_unicode_ci;
USE happy_reading;


DROP TABLE IF EXISTS `sysconfig`;
DROP TABLE IF EXISTS `properties`;
DROP TABLE IF EXISTS `user`;
DROP TABLE IF EXISTS `role`;
DROP TABLE IF EXISTS `authority`;


/*==============================================================*/
/* Table: `sysconfig` */
/*==============================================================*/
CREATE TABLE `sysconfig`
(
   id BIGINT(10) NOT NULL AUTO_INCREMENT,
   version double(14,10)  NULL COMMENT '版本号',
   releasedate datetime  NULL COMMENT '发布日期',
   PRIMARY KEY (id)
)ENGINE=InnoDB AUTO_INCREMENT=1 ROW_FORMAT=COMPRESSED DEFAULT CHARSET=utf8 COMMENT = '系统配置参数表';

/*==============================================================*/
/* Table: `properties` */
/*==============================================================*/
CREATE TABLE `properties`
(
   id BIGINT(10) NOT NULL AUTO_INCREMENT,
   name VARCHAR(20) NOT NULL COMMENT '配置名',
   value VARCHAR(2000)  NULL COMMENT '配置值',
   description VARCHAR(2000)  NULL COMMENT '备注',
   UNIQUE uk_properties_name (name),
   PRIMARY KEY (id)
)ENGINE=InnoDB AUTO_INCREMENT=1 ROW_FORMAT=COMPRESSED DEFAULT CHARSET=utf8 COMMENT = '配置表';

/*==============================================================*/
/* Table: `user` */
/*==============================================================*/
CREATE TABLE `user`
(
   id BIGINT(10) NOT NULL AUTO_INCREMENT,
   name VARCHAR(20)  NULL COMMENT '姓名',
   username VARCHAR(20) NOT NULL COMMENT '用户名',
   password VARCHAR(20)  NULL COMMENT '密码',
   state INT(4)  NULL COMMENT '0:NORMAL;-1:DELETED',
   roleid BIGINT(10)  NULL,
   description VARCHAR(2000)  NULL COMMENT '备注',
   UNIQUE uk_user_username (username),
   PRIMARY KEY (id)
)ENGINE=InnoDB AUTO_INCREMENT=1 ROW_FORMAT=COMPRESSED DEFAULT CHARSET=utf8 COMMENT = '用户表';

/*==============================================================*/
/* Table: `role` */
/*==============================================================*/
CREATE TABLE `role`
(
   id BIGINT(10) NOT NULL AUTO_INCREMENT,
   name VARCHAR(50) NOT NULL COMMENT '名称',
   state INT(4)  NULL COMMENT '0:NORMAL;-1:DELETED',
   isadmin bool  NULL default false COMMENT '是否管理员',
   authorities text  NULL COMMENT '分号相隔的权限名，例如：backendaction:device:index;backendaction:device:edit',
   description VARCHAR(2000)  NULL COMMENT '备注',
   UNIQUE uk_role_name (name),
   PRIMARY KEY (id)
)ENGINE=InnoDB AUTO_INCREMENT=1 ROW_FORMAT=COMPRESSED DEFAULT CHARSET=utf8 COMMENT = '角色表';

/*==============================================================*/
/* Table: `authority` */
/*==============================================================*/
CREATE TABLE `authority`
(
   id BIGINT(10) NOT NULL AUTO_INCREMENT,
   name VARCHAR(50) NOT NULL COMMENT '名称',
   label VARCHAR(50)  NULL COMMENT '标题',
   type INT(4)  NULL COMMENT '0:BACKEND_MENU;1:BACKEND_ACTION;2:WEB_MENU;3:WEB_ACTION',
   description VARCHAR(255)  NULL COMMENT '备注',
   UNIQUE uk_authority_name (name),
   PRIMARY KEY (id)
)ENGINE=InnoDB AUTO_INCREMENT=1 ROW_FORMAT=COMPRESSED DEFAULT CHARSET=utf8 COMMENT = '权限表';

ALTER TABLE `user` ADD CONSTRAINT fk_user_roleid FOREIGN KEY (roleid) REFERENCES `role`(id) ON UPDATE CASCADE ON DELETE RESTRICT;